title: Gizmo
syntax: GitHub Flavored Markdown
supportedLanguages:
  - en
  - ru
properties: []
# relatedLinks:
#  - url: https://Telegram.org
#    title: Telegram
#    icon: mail-question
name: new-catalog
repositoryName: new-catalog
sourceName: github.com
userInfo:
  mail: lericol@yahoo.com
  name: lericol
  id: lericol@yahoo.com
logo: logo.svg
language: en
style: blue-green
